import React from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowRight, Cpu, Mail, Users, BrainCircuit } from 'lucide-react'; // Added more icons for new sections

// Magic happens here: we directly import all routes generated by the plugin!
import routes from '~react-pages';

// A helper function to prettify pathnames
// For example: "/page1" becomes "Page 1", "QiMing-Moe" becomes "Qi Ming Moe"
function formatRouteName(path) {
 
  // ... The rest of the function remains unchanged
  if (path === '/') return 'Home';
  
  return path
    .replace('/', '') 
    .replace(/-/g, ' ') 
    .replace(/(\d+)/, ' $1')
    .replace(/(^\w|\s\w)/g, m => m.toUpperCase());
}

// Our auto-navigation component, now "Model Terminal"
const ModelTerminal = () => {
  // 1. Filter out routes we don't want to display in the navigation (like the homepage itself)
  const pagesToDisplay = routes.filter(route =>
    route.path !== '/' && !route.path.includes(':') // Filter out the homepage and dynamic routes
  );

  // 2. Sort the pages to ensure a correct order
  pagesToDisplay.sort((a, b) => a.path.localeCompare(b.path, undefined, { numeric: true }));

  // Animation variants for staggering the card display
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1,
      },
    },
  };

  const itemVariants = {
    hidden: { y: 20, opacity: 0 },
    visible: { y: 0, opacity: 1 },
  };

  return (
    <motion.div
      className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6"
      variants={containerVariants}
      initial="hidden"
      animate="visible"
    >
      {pagesToDisplay.map((page) => (
        <motion.div key={page.path} variants={itemVariants}>
          <Link
            to={page.path}
            className="group block p-6 bg-slate-800/50 border border-slate-700 rounded-xl shadow-lg hover:border-purple-500 hover:-translate-y-1 transition-all duration-300 h-full flex flex-col justify-between"
          >
            <div>
              <div className="flex justify-between items-center">
                <h3 className="text-2xl font-bold text-white">
                  {formatRouteName(page.path)}
                </h3>
                <Cpu className="h-6 w-6 text-slate-500 group-hover:text-purple-400 transition-colors" />
              </div>
              <p className="text-slate-400 mt-2">
                Model Instance ID: {page.path}
              </p>
            </div>
            <div className="mt-4 text-purple-400 flex items-center font-semibold opacity-0 group-hover:opacity-100 transition-opacity duration-300">
              Enter World <ArrowRight className="ml-2 h-5 w-5" />
            </div>
          </Link>
        </motion.div>
      ))}
    </motion.div>
  );
};

// The entire homepage component
export default function IndexPage() {
  return (
    <div className="bg-slate-900 min-h-screen text-white p-8 sm:p-12 font-sans overflow-hidden">
      <div className="max-w-7xl mx-auto">
        <header className="text-center mb-16">
          <motion.h1
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="text-5xl md:text-6xl font-extrabold tracking-tight bg-clip-text text-transparent bg-gradient-to-r from-indigo-400 via-purple-400 to-pink-400"
          >
            Qiming AI Model Matrix
          </motion.h1>
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
            className="mt-4 text-lg text-slate-300 max-w-3xl mx-auto"
          >
            Welcome to the Qiming Terminal. This is the assembly point for all AI personas, from "Moe" creative sparks to professional business insights. Click a card below to launch an instance and explore a unique world built by AI.
          </motion.p>
          {/* --- Added Note --- */}
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.3 }}
            className="mt-4 text-md text-slate-400 max-w-3xl mx-auto italic"
          >
            Please note: All content showcased on this site, including the names, descriptions, and interactions of the AI personas, has been generated by the QiMing series of models.
          </motion.p>
        </header>

        <main>
          <ModelTerminal />
        </main>

        <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.4 }}
            className="mt-16 text-center"
        >
            <h2 className="text-3xl font-bold text-white mb-8">Explore Our Models</h2>
            <a
                href="https://huggingface.co/aifeifei798"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center justify-center px-8 py-4 bg-slate-800/50 border border-slate-700 rounded-xl shadow-lg hover:border-purple-500 hover:-translate-y-1 transition-all duration-300 text-white font-semibold"
            >
                <BrainCircuit className="h-6 w-6 mr-3 text-purple-400" />
                View on Hugging Face
                <ArrowRight className="ml-3 h-5 w-5" />
            </a>
        </motion.div>


        <footer className="mt-16 pt-8 border-t border-slate-800 text-center text-slate-400">
          <h2 className="text-2xl font-bold text-white mb-6">Contact Us</h2>
          <div className="flex flex-col sm:flex-row justify-center items-center gap-8">
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.5, delay: 0.6 }}
              className="flex items-center"
            >
              <Mail className="h-5 w-5 mr-3 text-purple-400" />
              <strong>General Inquiries:</strong>
              <a href="mailto:contact@feimatrix.com" className="ml-2 text-indigo-400 hover:underline">contact@feimatrix.com</a>
            </motion.div>
            <motion.div
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.5, delay: 0.8 }}
              className="flex items-center"
            >
              <Users className="h-5 w-5 mr-3 text-purple-400" />
              <strong>Project Partnerships:</strong>
              <a href="mailto:projects@feimatrix.com" className="ml-2 text-indigo-400 hover:underline">projects@feimatrix.com</a>
            </motion.div>
          </div>
        </footer>
      </div>
    </div>
  );
}